### ISSUE TITLE
Unable to run gextoolbox

### ISSUE THREAD

**Issue by Rot-gut** [shawngmc/game-extraction-toolbox#54]
Using cmd.exe on Windows with Python 3.8, after ensuring I had pip and pipx set up and game-extraction-toolbox installed, I get the following error when running gextoolbox --help:

`C:\Users\nukac>gextoolbox --help
Traceback (most recent call last):
  File "c:\users\nukac\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nukac\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\nukac\AppData\Local\Programs\Python\Python38\Scripts\gextoolbox.exe\__main__.py", line 4, in <module>
  File "c:\users\nukac\appdata\local\programs\python\python38\lib\site-packages\gex\toolbox.py", line 6, in <module>
    from gex.commands.file.file import file
  File "c:\users\nukac\appdata\local\programs\python\python38\lib\site-packages\gex\commands\file\file.py", line 3, in <module>
    from .deinterleave import deinterleave
  File "c:\users\nukac\appdata\local\programs\python\python38\lib\site-packages\gex\commands\file\deinterleave.py", line 5, in <module>
    from gex.lib.utils.blob import transforms
  File "c:\users\nukac\appdata\local\programs\python\python38\lib\site-packages\gex\lib\utils\blob\transforms.py", line 20, in <module>
    def merge(chunks: list[bytes]) -> bytearray:
TypeError: 'type' object is not subscriptable`

**Comment by shawngmc** [comment]
OK, did a bit of digging, and it appears a type hinting feature I'm using actually requires Python 3.9.
I'm going to move the minimum required version up, but in the meantime, do you get the issue under Python 3.9+?

**Comment by shawngmc** [comment]
Closing due to lack of follow up.
