### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by JohnGhostly** [shawngmc/game-extraction-toolbox#60]
Having the same issue as mentioned in https://github.com/shawngmc/game-extraction-toolbox/issues/54 

`Traceback (most recent call last):
  File "c:\users\(username)\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\(username)\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\(username)\.local\bin\gextoolbox.exe\__main__.py", line 4, in <module>
  File "C:\Users\(username)\.local\pipx\venvs\game-extraction-toolbox\lib\site-packages\gex\toolbox.py", line 6, in <module>
    from gex.commands.file.file import file
  File "C:\Users\(username)\.local\pipx\venvs\game-extraction-toolbox\lib\site-packages\gex\commands\file\file.py", line 3, in <module>
    from .deinterleave import deinterleave
  File "C:\Users\(username)\.local\pipx\venvs\game-extraction-toolbox\lib\site-packages\gex\commands\file\deinterleave.py", line 5, in <module>
    from gex.lib.utils.blob import transforms
  File "C:\Users\(username)\.local\pipx\venvs\game-extraction-toolbox\lib\site-packages\gex\lib\utils\blob\transforms.py", line 20, in <module>
    def merge(chunks: list[bytes]) -> bytearray:
TypeError: 'type' object is not subscriptable
PS C:\Users\(username)\.local\pipx\venvs\game-extraction-toolbox\Scripts>
`
I've tried both python 3.10.10 and 3.10.11 and ran cmd from both the path in which gextoolbox.exe is in as well as from a standard command prompt. any command gives the same issue.

**Comment by shawngmc** [comment]
The traceback is showing python 3.8. Can you try running removing python 3.8, then installing PIPX and GEX with the newer version of Python? I suspect that pipx and/or gex system paths are taking precedence...

**Comment by JohnGhostly** [comment]
On uninstall I get this error:
``C:\Windows\System32>pipx install game-extraction-toolbox
Fatal error in launcher: Unable to create process using '"c:\users\(USERNAME)\appdata\local\programs\python\python38\python.exe"  "c:\users\(USERNAME)appdata\roaming\python\python38\scripts\pipx.exe" install game-extraction-toolbox': The system cannot find the file specified.``

**Comment by shawngmc** [comment]
It looks like it's trying to use pipx from Python 3.8.

Try reinstalling pipx via ```python -m pip install pipx```.

**Comment by JohnGhostly** [comment]
Seems it cant find the newest version of python when I attempt to reinstall. I did make sure to install the latest version

**Comment by JohnGhostly** [comment]
So I figured it out, it doesn't matter what python version you have so long as its newer than python38. 
All I had to do was go into C:\Users<your username>\AppData\Local\Programs\Python and rename my python 311 (or presumably whichever version of python you might have) and rename it to python38
