### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by PPlayer31** [shawngmc/game-extraction-toolbox#80]
I Installed python 3.12.5 then verified it with python --version
then i ran:
python -m pip install --user pipx
python -m pipx ensurepath
pipx --version

after this i ran pipx install game-extraction-toolbox
but when i used gextoolbox version i got this:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\oikon\.local\bin\gextoolbox.exe\__main__.py", line 4, in <module>
  File "C:\Users\Oikon\pipx\venvs\game-extraction-toolbox\Lib\site-packages\gex\toolbox.py", line 10, in <module>
    from gex.commands.version import version
  File "C:\Users\Oikon\pipx\venvs\game-extraction-toolbox\Lib\site-packages\gex\commands\version.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

what am I supposed to do to fix it?

**Comment by PPlayer31** [comment]
Im sure someone faced this in the past...

**Comment by PPlayer31** [comment]
LOL I FORGOT IT DOESNT WORK WITH 3.12 LOLLLLLL
